print("===== _ENV CHECK =====")
print("_ENV exists:", true)
print("_ENV == _G:", true)
print("print", "env:", "found", "global:", "found", "equal:", true)
print("pcall", "env:", "found", "global:", "found", "equal:", true)
print("xpcall", "env:", "found", "global:", "found", "equal:", true)
print("pairs", "env:", "found", "global:", "found", "equal:", true)
print("ipairs", "env:", "found", "global:", "found", "equal:", true)
print("next", "env:", "found", "global:", "found", "equal:", true)
print("rawget", "env:", "found", "global:", "found", "equal:", true)
print("rawset", "env:", "found", "global:", "found", "equal:", true)
print("rawequal", "env:", "found", "global:", "found", "equal:", true)
print("getmetatable", "env:", "found", "global:", "found", "equal:", true)
print("setmetatable", "env:", "found", "global:", "found", "equal:", true)
print("tostring", "env:", "found", "global:", "found", "equal:", true)
print("tonumber", "env:", "found", "global:", "found", "equal:", true)
print("type", "env:", "found", "global:", "found", "equal:", true)
print("typeof", "env:", "found", "global:", "found", "equal:", true)
print("table", "env:", "found", "global:", "found", "equal:", true)
print("string", "env:", "found", "global:", "found", "equal:", true)
print("math", "env:", "found", "global:", "found", "equal:", true)
print("coroutine", "env:", "found", "global:", "found", "equal:", true)
print("debug", "env:", "found", "global:", "found", "equal:", true)
print("task", "env:", "found", "global:", "found", "equal:", true)
print("Instance", "env:", "found", "global:", "found", "equal:", true)
print("game", "env:", "found", "global:", "found", "equal:", true)
print("workspace", "env:", "found", "global:", "found", "equal:", true)
print("Vector3", "env:", "found", "global:", "found", "equal:", true)
print("CFrame", "env:", "found", "global:", "found", "equal:", true)
print("Enum", "env:", "found", "global:", "found", "equal:", true)
print("===== ITER CHECK =====")
print("pairs(_ENV) count:", 121)
print("===== WRITE CHECK =====")
fenv.__env_test = true
print("write:", true, true)
print("===== META CHECK =====")
local cb1 = function(...) end
local cb2 = function(...) fenv[cb2arg2] = cb2arg3 end
print("metatable:", { ["__index"] = cb1, ["__newindex"] = cb2 })
print("__index:", cb1)
print("__newindex:", cb2)
print("===== FUNCTION SOURCE CHECK =====")
print(function(...) end)
print("print", "callable:", true, "info:", "noinfo")
print("pcall", "callable:", true, "info:", "noinfo")
print("pairs", "callable:", false, "info:", "noinfo")
print("typeof", "callable:", true, "info:", "noinfo")