print("crypt", {
    ["encrypt"] = function(Instance_cb1arg1, Instance_cb1arg2, Instance_cb1arg3) end,
    ["b64_encode"] = function(Instance_cb2arg1, Instance_cb2arg2, Instance_cb2arg3)
        crypt.base64encode(Instance_cb2arg1) 
    end,
    ["decrypt"] = function(Instance_cb4arg1, Instance_cb4arg2, Instance_cb4arg3) end,
    ["b64_decode"] = function(Instance_cb5arg1, Instance_cb5arg2, Instance_cb5arg3)
        crypt.base64decode(Instance_cb5arg1) 
    end,
    ["hash"] = function(Instance_cb7arg1, Instance_cb7arg2, Instance_cb7arg3) end
})
print("request", function(Instance_cb8arg1, Instance_cb8arg2, Instance_cb8arg3)
    syn.request(Instance_cb8arg1) 
end)
print("queue_on_teleport", function(Instance_cb10arg1, Instance_cb10arg2, Instance_cb10arg3)
    syn.queue_on_teleport(Instance_cb10arg1) 
end)
print("unprotect_gui", function(Instance_cb11arg1, Instance_cb11arg2, Instance_cb11arg3)
    syn.unprotect_gui(Instance_cb11arg1) 
end)
print("protect_gui", function(Instance_cb12arg1, Instance_cb12arg2, Instance_cb12arg3)
    syn.protect_gui(Instance_cb12arg1) 
end)
print("dumpheap", function(Instance_cb13arg1, Instance_cb13arg2, Instance_cb13arg3) end)
print("getconstant", function(Instance_cb14arg1, Instance_cb14arg2, Instance_cb14arg3) end)
print("getproto", function(Instance_cb15arg1, Instance_cb15arg2, Instance_cb15arg3) end)
print("setmemorycategory", function(Instance_cb16arg1, Instance_cb16arg2, Instance_cb16arg3) end)
print("profilebegin", function(Instance_cb17arg1, Instance_cb17arg2, Instance_cb17arg3) end)
print("traceback", function(Instance_cb18arg1, Instance_cb18arg2, Instance_cb18arg3) end)
print("getstack", function(Instance_cb20arg1, Instance_cb20arg2, Instance_cb20arg3) end)
print("getupvalues", function(Instance_cb21arg1, Instance_cb21arg2, Instance_cb21arg3) end)
print("getupvalue", function(Instance_cb22arg1, Instance_cb22arg2, Instance_cb22arg3) end)
print("resetmemorycategory", function(Instance_cb23arg1, Instance_cb23arg2, Instance_cb23arg3) end)
print("setstack", function(Instance_cb24arg1, Instance_cb24arg2, Instance_cb24arg3) end)
print("getprotos", function(Instance_cb25arg1, Instance_cb25arg2, Instance_cb25arg3) end)
print("profileend", function(Instance_cb26arg1, Instance_cb26arg2, Instance_cb26arg3) end)
print("info", function(Instance_cb27arg1, Instance_cb27arg2, Instance_cb27arg3) end)
print("getinfo", function(Instance_cb28arg1, Instance_cb28arg2, Instance_cb28arg3) end)
print("setupvalue", function(Instance_cb29arg1, Instance_cb29arg2, Instance_cb29arg3) end)
print("setconstant", function(Instance_cb30arg1, Instance_cb30arg2, Instance_cb30arg3) end)
print("getregistry", debug.getregistry)
print("getconstants", function(Instance_cb31arg1, Instance_cb31arg2, Instance_cb31arg3) end)