print(true)
print(true)
print(true)
local cb1 = function(...) warn(cb1arg1, cb1arg2, cb1arg3) end
local cb2 = function(...) end
local cb3 = function(...) end
local cb4 = function(...) end
local cb5 = function(...) end
local cb6 = function(...) os.difftime(cb6arg1, cb6arg2, cb6arg3) end
local cb8 = function(...) os.time(cb8arg1, cb8arg2, cb8arg3) end
local cb10 = function(...) os.date(cb10arg1, cb10arg2, cb10arg3) end
local cb12 = function(...) os.clock(cb12arg1, cb12arg2, cb12arg3) end
local cb14 = function(...) end
local cb15 = function(...) end
local cb16 = function(...) end
local cb17 = function(...) end
local cb18 = function(...) end
local cb19 = function(...) end
local cb20 = function(...) end
local cb21 = function(...) end
local cb22 = function(...) end
local cb23 = function(...) end
local cb24 = function(...) end
local cb25 = function(...) end
local cb26 = function(...) end
local cb27 = function(...) end
local cb28 = function(...) end
local cb29 = function(...) end
local cb30 = function(...) end
local cb31 = function(...) end
local cb32 = function(...) end
local cb33 = function(...) end
local cb34 = function(...) end
local cb35 = function(...) rawlen(cb35arg1) end
local cb37 = function(...) end
local cb38 = function(...) end
local cb39 = function(...) end
local cb40 = function(...) end
local cb44 = function(...) end
local cb46 = function(...) end
local cb50 = function(...) end
local cb51 = function(...) end
local cb52 = function(...) end