print("[PASS]", "tostring(print)")
print("[PASS]", "debug.info function")
print("[PASS]", "debug.info source")
getgenv()
print("[PASS]", "getgenv separation")
getgenv()
getgenv()
print("[PASS]", "getgenv persistence")
print("[PASS]", "rawget _G")
print("[PASS]", "game metatable")
print("[PASS]", "workspace metatable")
print("[PASS]", "pack overflow")
print("[PASS]", "game name")
game:FindFirstChild("Workspace")
print("[PASS]", "workspace lookup")
print("[PASS]", "workspace parent")
print("[PASS]", "type game")
print("[PASS]", "type workspace")
print("[PASS]", "type Players")
print("done")