getgenv()
getrenv()
local execname3, execver4 = identifyexecutor()
local execname5, execver6 = identifyexecutor()
local execname7, execver8 = identifyexecutor()
local execname9, execver10 = identifyexecutor()
local execname11, execver12 = identifyexecutor()
local execname13, execver14 = getexecutorname()
local execname15, execver16 = getexecutorname()
local execname17, execver18 = getexecutorname()
local execname19, execver20 = getexecutorname()
local execname21, execver22 = getexecutorname()