print("getgenv")
print("getrenv")
print("getgc")
print("getreg")
print("hookfunction")
print("newcclosure")
print("checkcaller")
print("islclosure")
print("iscclosure")
print("getrawmetatable")
print("setrawmetatable")
print("clonefunction")
print("API: 12/12 (100%)")