print("[PASS]", "tostring(print)")
print("[PASS]", "debug.info function")
print("[PASS]", "debug.info source")
getgenv()
print("[PASS]", "getgenv separation")
getgenv()
getgenv()
warn("[FAIL]", "getgenv persistence", "assertion failed!")
print("[PASS]", "rawget _G")
print("[PASS]", "game metatable")
print("[PASS]", "workspace metatable")
warn("[FAIL]", "pack overflow", "[string \"script\"]:40: invalid argument #2 to 'pack' (unsigned overflow)")
print("[PASS]", "game name")
game:FindFirstChild("Workspace")
print("[PASS]", "workspace lookup")
print("[PASS]", "workspace parent")
warn("[FAIL]", "type game", "assertion failed!")
warn("[FAIL]", "type workspace", "assertion failed!")
warn("[FAIL]", "type Players", "assertion failed!")
print("done")