print("\nUNC Environment Check")
print("Core = official sUNC documented functions only")
print("Optional = documented executor extensions; behavior-tested and not counted against UNC score")
print("Aliases are fallback-only and exists-only checks are not counted as passes\n")
print("\xe2\x9c\x85 checkcaller")
print("\xe2\x9c\x85 clonefunction")
warn("\xe2\x9d\x8c missing core: getfunctionhash -> getfunctionhash")
warn("\xe2\x9b\x94 hookfunction \xe2\x80\xa2 hookfunction did not replace behavior")
print("\xe2\x9c\x85 hookmetamethod")
print("\xe2\x9c\x85 iscclosure")
print("\xe2\x9c\x85 isexecutorclosure")
print("\xe2\x9c\x85 islclosure")
print("\xe2\x9c\x85 loadstring")
print("\xe2\x9c\x85 newcclosure")
warn("\xe2\x9d\x8c missing core: restorefunction -> restorefunction")
warn("\xe2\x9b\x94 debug.getconstant \xe2\x80\xa2 could not find expected constant")
warn("\xe2\x9b\x94 debug.getconstants \xe2\x80\xa2 constants table did not include expected string")
print("\xe2\x9c\x85 debug.getproto")
print("\xe2\x9c\x85 debug.getprotos")
print("\xe2\x9c\x85 debug.getstack")
warn("\xe2\x9b\x94 debug.getupvalue \xe2\x80\xa2 debug.getupvalue returned the wrong value")
warn("\xe2\x9b\x94 debug.getupvalues \xe2\x80\xa2 upvalue was not present")
warn("\xe2\x9b\x94 debug.setconstant \xe2\x80\xa2 debug.setconstant did not change the constant")
warn("\xe2\x9b\x94 debug.setstack \xe2\x80\xa2 debug.setstack did not update the stack value")
warn("\xe2\x9b\x94 debug.setupvalue \xe2\x80\xa2 debug.setupvalue did not update the upvalue")
cleardrawcache()
print("\xe2\x9c\x85 cleardrawcache")
local drawsquare1 = Drawing.new("Square")
setrenderproperty(drawsquare1, "Visible", false)
getrenderproperty(drawsquare1, "Visible")
drawsquare1:Remove()
drawsquare1:Remove()
print("\xe2\x9c\x85 getrenderproperty")
local drawsquare3 = Drawing.new("Square")
isrenderobj(drawsquare3)
drawsquare3:Remove()
drawsquare3:Remove()
print("\xe2\x9c\x85 isrenderobj")
local drawsquare5 = Drawing.new("Square")
setrenderproperty(drawsquare5, "Visible", false)
drawsquare5:Remove()
drawsquare5:Remove()
print("\xe2\x9c\x85 setrenderproperty")
print("\xe2\x9c\x85 base64decode [crypt.base64decode]")
print("\xe2\x9c\x85 base64encode [crypt.base64encode]")
print("\xe2\x9c\x85 lz4compress")
print("\xe2\x9c\x85 lz4decompress")
print("\xe2\x9c\x85 getgc")
print("\xe2\x9c\x85 getgenv")
print("\xe2\x9c\x85 getreg")
warn("\xe2\x9b\x94 getrenv \xe2\x80\xa2 getrenv().game must match game")
warn("\xe2\x9d\x8c missing core: filtergc -> filtergc")
writefile(".unc_test_0_append.txt", "a")
appendfile(".unc_test_0_append.txt", "b")
readfile(".unc_test_0_append.txt")
delfile(".unc_test_0_append.txt")
print("\xe2\x9c\x85 appendfile")
writefile(".unc_test_0_del.txt", "x")
isfile(".unc_test_0_del.txt")
delfile(".unc_test_0_del.txt")
isfile(".unc_test_0_del.txt")
print("\xe2\x9c\x85 delfile")
makefolder(".unc_test_0_folder_del")
isfolder(".unc_test_0_folder_del")
delfolder(".unc_test_0_folder_del")
isfolder(".unc_test_0_folder_del")
print("\xe2\x9c\x85 delfolder")
writefile(".unc_test_0_asset.txt", "asset")
delfile(".unc_test_0_asset.txt")
print("\xe2\x9c\x85 getcustomasset")
writefile(".unc_test_0_isfile.txt", "x")
isfile(".unc_test_0_isfile.txt")
delfile(".unc_test_0_isfile.txt")
print("\xe2\x9c\x85 isfile")
makefolder(".unc_test_0_isfolder")
isfolder(".unc_test_0_isfolder")
delfolder(".unc_test_0_isfolder")
print("\xe2\x9c\x85 isfolder")
isfolder(".unc_test_0")
makefolder(".unc_test_0")
writefile(".unc_test_0/a.txt", "x")
listfiles(".unc_test_0")
print("\xe2\x9c\x85 listfiles")
writefile(".unc_test_0_load.lua", "return 123")
loadfile(".unc_test_0_load.lua")
delfile(".unc_test_0_load.lua")
print("\xe2\x9c\x85 loadfile")
makefolder(".unc_test_0_mk")
isfolder(".unc_test_0_mk")
delfolder(".unc_test_0_mk")
print("\xe2\x9c\x85 makefolder")
writefile(".unc_test_0_read.txt", "read-ok")
readfile(".unc_test_0_read.txt")
delfile(".unc_test_0_read.txt")
print("\xe2\x9c\x85 readfile")
writefile(".unc_test_0_write.txt", "write-ok")
readfile(".unc_test_0_write.txt")
delfile(".unc_test_0_write.txt")
print("\xe2\x9c\x85 writefile")
game:GetService("CoreGui")
print("\xe2\x9c\x85 cloneref")
print("\xe2\x9c\x85 compareinstances")
print("\xe2\x8f\xba\xef\xb8\x8f fireclickdetector \xe2\x80\xa2 exists; exists-only by request; live signal is not fired")
print("\xe2\x8f\xba\xef\xb8\x8f fireproximityprompt \xe2\x80\xa2 exists; exists-only by request; live prompt is not fired")
print("\xe2\x8f\xba\xef\xb8\x8f firetouchinterest \xe2\x80\xa2 exists; exists-only by request; live touch is not fired")
instBindableFunction20.OnInvoke = function(...) end
Instance.new("BindableFunction"):Destroy()
print("\xe2\x9c\x85 getcallbackvalue")
game:GetService("CoreGui")
print("\xe2\x9c\x85 gethui")
print("\xe2\x9c\x85 getinstances")
print("\xe2\x9c\x85 getnilinstances")
print("\xe2\x9c\x85 getnamecallmethod")
print("\xe2\x9c\x85 getrawmetatable")
print("\xe2\x9c\x85 isreadonly")
print("\xe2\x9c\x85 setrawmetatable")
print("\xe2\x9c\x85 setreadonly")
print("\xe2\x9c\x85 identifyexecutor")
request({ ["Method"] = "GET", ["Url"] = "https://example.com" })
print("\xe2\x9c\x85 request")
Instance.new("Fire"):Destroy()
print("\xe2\x9c\x85 gethiddenproperty")
print("\xe2\x9c\x85 getthreadidentity")
Instance.new("Fire"):Destroy()
print("\xe2\x9c\x85 isscriptable")
Instance.new("Fire"):Destroy()
print("\xe2\x9c\x85 sethiddenproperty")
Instance.new("Fire"):Destroy()
print("\xe2\x9c\x85 setscriptable")
print("\xe2\x9c\x85 setthreadidentity")
warn("\xe2\x9d\x8c missing core: getcallingscript -> getcallingscript")
print("\xe2\x9c\x85 getloadedmodules")
print("\xe2\x9c\x85 getrunningscripts")
game:GetService("Players")
game.Players.LocalPlayer:FindFirstChildOfClass("PlayerGui")
game:GetService("ReplicatedFirst")
game:GetService("ReplicatedStorage")
game.Players.LocalPlayer:FindFirstChildOfClass("PlayerScripts"):FindFirstChildWhichIsA("LocalScript", true)
print("\xe2\x9c\x85 getscriptbytecode")
game:GetService("Players")
game.Players.LocalPlayer:FindFirstChildOfClass("PlayerGui")
game:GetService("ReplicatedFirst")
game:GetService("ReplicatedStorage")
game.Players.LocalPlayer:FindFirstChildOfClass("PlayerScripts"):FindFirstChildWhichIsA("LocalScript", true)
print("\xe2\x9c\x85 getscriptclosure")
game:GetService("Players")
game.Players.LocalPlayer:FindFirstChildOfClass("PlayerGui")
game:GetService("ReplicatedFirst")
game:GetService("ReplicatedStorage")
print("\xe2\x9c\x85 getscripthash")
print("\xe2\x9c\x85 getscripts")
game:GetService("Players")
game.Players.LocalPlayer:FindFirstChildOfClass("PlayerGui")
game:GetService("ReplicatedFirst")
game:GetService("ReplicatedStorage")
game.Players.LocalPlayer:FindFirstChildOfClass("PlayerScripts"):FindFirstChildWhichIsA("LocalScript", true)
print("\xe2\x9c\x85 getsenv")
warn("\xe2\x9d\x8c missing core: firesignal -> firesignal")
local instBindableEvent58 = Instance.new("BindableEvent")
instBindableEvent58.Event:Connect(function(...) end):Disconnect()
instBindableEvent58:Destroy()
print("\xe2\x9c\x85 getconnections")
warn("\xe2\x9d\x8c missing core: replicatesignal -> replicatesignal")
local ws63 = WebSocket.connect("wss://ws.postman-echo.com/raw")
ws63:Close()
ws63:Close()
print("\xe2\x9c\x85 WebSocket.connect")
print("\nOptional documented extension checks")
local instBindableFunction64 = Instance.new("BindableFunction")
instBindableFunction64.OnInvoke = function(...) end
local service66 = game:GetService("StarterGui")
local setCore67 = service66.SetCore
setCore67(service66, "SendNotification", {
    ["Button2"] = "No",
    ["Title"] = "UNC rconsole tests",
    ["Button1"] = "Yes",
    ["Text"] = "Some executors crash on rconsole. Test rconsole functions?",
    ["Callback"] = instBindableFunction64,
    ["Duration"] = 15
})
instBindableFunction64:Destroy()
setCore67(game:GetService("StarterGui"), "SendNotification", {
    ["Text"] = "Skipped rconsole checks.",
    ["Title"] = "UNC rconsole tests",
    ["Duration"] = 5
})
print("[UNC] UNC rconsole tests: Skipped rconsole checks.")
print("\xe2\x8f\xad\xef\xb8\x8f rconsolecreate \xe2\x80\xa2 rconsole skipped: user chose no")
print("\xe2\x8f\xba\xef\xb8\x8f optional missing: rconsolesettitle -> rconsolesettitle")
print("\xe2\x8f\xad\xef\xb8\x8f rconsoleprint \xe2\x80\xa2 rconsole skipped: user chose no")
print("\xe2\x8f\xad\xef\xb8\x8f rconsoleinfo \xe2\x80\xa2 rconsole skipped: user chose no")
print("\xe2\x8f\xad\xef\xb8\x8f rconsolewarn \xe2\x80\xa2 rconsole skipped: user chose no")
print("\xe2\x8f\xba\xef\xb8\x8f optional missing: rconsoleerror -> rconsoleerror")
print("\xe2\x8f\xad\xef\xb8\x8f rconsoleclear \xe2\x80\xa2 rconsole skipped: user chose no")
print("\xe2\x8f\xad\xef\xb8\x8f rconsoleinput \xe2\x80\xa2 rconsole skipped: user chose no")
print("\xe2\x8f\xad\xef\xb8\x8f rconsoledestroy \xe2\x80\xa2 rconsole skipped: user chose no")
print("\xe2\x9c\x85 crypt.base64encode")
print("\xe2\x9c\x85 crypt.base64decode")
print("\xe2\x9c\x85 crypt.encrypt")
print("\xe2\x9c\x85 crypt.decrypt")
print("\xe2\x9c\x85 crypt.generatebytes")
print("\xe2\x9c\x85 crypt.generatekey")
print("\xe2\x9c\x85 crypt.hash")
print("\xe2\x8f\xba\xef\xb8\x8f optional missing: crypt.hmac -> crypt.hmac")
print("\xe2\x8f\xba\xef\xb8\x8f optional missing: crypt.random -> crypt.random")
print("\xe2\x8f\xba\xef\xb8\x8f optional missing: dofile -> dofile")
print("\xe2\x9c\x85 debug.getinfo")
print("\xe2\x8f\xba\xef\xb8\x8f optional missing: debug.getcallstack -> debug.getcallstack")
print("\xe2\x8f\xba\xef\xb8\x8f optional missing: debug.getregistry -> debug.getregistry")
print("\xe2\x8f\xba\xef\xb8\x8f optional missing: debug.getsafeenv -> debug.getsafeenv")
print("\xe2\x8f\xba\xef\xb8\x8f optional missing: debug.isvalidlevel -> debug.isvalidlevel")
print("\xe2\x8f\xba\xef\xb8\x8f optional missing: debug.setinfo -> debug.setinfo")
print("\xe2\x8f\xba\xef\xb8\x8f optional missing: debug.setname -> debug.setname")
print("\xe2\x8f\xba\xef\xb8\x8f optional missing: debug.setsafeenv -> debug.setsafeenv")
print("\xe2\x9c\x85 Drawing.Fonts")
local drawsquare72 = Drawing.new("Square")
drawsquare72:Remove()
drawsquare72:Remove()
print("\xe2\x9c\x85 Drawing.new")
print("\xe2\x8f\xba\xef\xb8\x8f optional missing: DrawingImmediate.GetPaint -> DrawingImmediate.GetPaint")
print("\xe2\x9c\x85 isrbxactive")
print("\xe2\x8f\xba\xef\xb8\x8f optional missing: keypress -> keypress")
print("\xe2\x8f\xba\xef\xb8\x8f optional missing: keyrelease -> keyrelease")
print("\xe2\x8f\xba\xef\xb8\x8f optional missing: keytap -> keytap")
print("\xe2\x8f\xba\xef\xb8\x8f optional missing: mouse1click -> mouse1click")
print("\xe2\x8f\xba\xef\xb8\x8f optional missing: mouse1press -> mouse1press")
print("\xe2\x8f\xba\xef\xb8\x8f optional missing: mouse1release -> mouse1release")
print("\xe2\x8f\xba\xef\xb8\x8f optional missing: mouse2click -> mouse2click")
print("\xe2\x8f\xba\xef\xb8\x8f optional missing: mouse2press -> mouse2press")
print("\xe2\x8f\xba\xef\xb8\x8f optional missing: mouse2release -> mouse2release")
print("\xe2\x8f\xba\xef\xb8\x8f optional missing: mousemoveabs -> mousemoveabs")
print("\xe2\x8f\xba\xef\xb8\x8f optional missing: mousemoverel -> mousemoverel")
print("\xe2\x8f\xba\xef\xb8\x8f optional missing: mousescroll -> mousescroll")
print("\xe2\x8f\xba\xef\xb8\x8f optional missing: isfunctionhooked -> isfunctionhooked")
print("\xe2\x8f\xba\xef\xb8\x8f optional missing: isnewcclosure -> isnewcclosure")
print("\xe2\x8f\xba\xef\xb8\x8f optional missing: isourthread -> isourthread")
print("\xe2\x8f\xba\xef\xb8\x8f optional missing: newlclosure -> newlclosure")
print("\xe2\x8f\xba\xef\xb8\x8f optional missing: setstackhidden -> setstackhidden")
print("\xe2\x8f\xba\xef\xb8\x8f optional missing: getrendersteppedlist -> getrendersteppedlist")
print("\xe2\x8f\xba\xef\xb8\x8f optional missing: makereadonly -> makereadonly")
print("\xe2\x8f\xba\xef\xb8\x8f optional missing: makewritable -> makewritable")
print("\xe2\x8f\xba\xef\xb8\x8f optional missing: setnamecallmethod -> setnamecallmethod")
print("\xe2\x8f\xba\xef\xb8\x8f optional missing: clearteleportqueue -> clearteleportqueue")
print("\xe2\x8f\xba\xef\xb8\x8f optional missing: decompile -> decompile")
print("\xe2\x8f\xba\xef\xb8\x8f optional missing: getfflag -> getfflag")
print("\xe2\x8f\xba\xef\xb8\x8f optional missing: getfflagtype -> getfflagtype")
print("\xe2\x8f\xba\xef\xb8\x8f optional missing: getfpscap -> getfpscap")
print("\xe2\x8f\xba\xef\xb8\x8f optional missing: gethwid -> gethwid")
print("\xe2\x8f\xba\xef\xb8\x8f optional missing: getobjects -> getobjects")
print("\xe2\x8f\xba\xef\xb8\x8f optional missing: httpget -> httpget")
print("\xe2\x9c\x85 messagebox \xe2\x80\xa2 opened with flags=0; returned 1")
print("\xe2\x9c\x85 queueonteleport")
setclipboard("UNC_TEST")
print("\xe2\x9c\x85 setclipboard")
print("\xe2\x8f\xba\xef\xb8\x8f optional missing: setfflag -> setfflag")
setfpscap(60)
print("\xe2\x9c\x85 setfpscap")
setrbxclipboard("UNC_TEST")
print("\xe2\x9c\x85 setrbxclipboard")
print("\xe2\x8f\xba\xef\xb8\x8f optional missing: gethiddenproperties -> gethiddenproperties")
print("\xe2\x8f\xba\xef\xb8\x8f optional missing: getproperties -> getproperties")
print("\xe2\x8f\xba\xef\xb8\x8f optional missing: getbspval -> getbspval")
print("\xe2\x8f\xba\xef\xb8\x8f optional missing: getpcd -> getpcd")
print("\xe2\x8f\xba\xef\xb8\x8f optional missing: getproximitypromptduration -> getproximitypromptduration")
print("\xe2\x8f\xba\xef\xb8\x8f optional missing: setproximitypromptduration -> setproximitypromptduration")
print("\xe2\x8f\xba\xef\xb8\x8f optional missing: getsimulationradius -> getsimulationradius")
print("\xe2\x8f\xba\xef\xb8\x8f optional missing: setsimulationradius -> setsimulationradius")
print("\xe2\x8f\xba\xef\xb8\x8f optional missing: isnetworkowner -> isnetworkowner")
print("\xe2\x8f\xba\xef\xb8\x8f optional missing: getscriptfromthread -> getscriptfromthread")
print("\xe2\x8f\xba\xef\xb8\x8f optional missing: getscriptthread -> getscriptthread")
print("\xe2\x8f\xba\xef\xb8\x8f optional missing: cansignalreplicate -> cansignalreplicate")
print("\xe2\x8f\xba\xef\xb8\x8f optional missing: getconnection -> getconnection")
print("\xe2\x8f\xba\xef\xb8\x8f optional missing: getsignalarguments -> getsignalarguments")
print("\xe2\x8f\xba\xef\xb8\x8f optional missing: getsignalargumentsinfo -> getsignalargumentsinfo")
print("\xe2\x8f\xba\xef\xb8\x8f optional missing: getsignalwhitelist -> getsignalwhitelist")
print("\xe2\x8f\xba\xef\xb8\x8f optional missing: Regex.Escape -> Regex.Escape")
print("\xe2\x8f\xba\xef\xb8\x8f optional missing: Regex.new -> Regex.new")
print("\xe2\x8f\xba\xef\xb8\x8f optional missing: oth.hook -> oth.hook")
print("\xe2\x8f\xba\xef\xb8\x8f optional missing: oth.unhook -> oth.unhook")
print("\xe2\x8f\xba\xef\xb8\x8f optional missing: oth.get_original_thread -> oth.get_original_thread")
print("\xe2\x8f\xba\xef\xb8\x8f optional missing: oth.get_root_callback -> oth.get_root_callback")
print("\xe2\x8f\xba\xef\xb8\x8f optional missing: oth.is_hook_thread -> oth.is_hook_thread")
delfolder(".unc_test_0")
print("\nUNC Summary")
print("\xe2\x9c\x85 Core passes: 61")
print("\xe2\x9b\x94 Core behavior fails: 9")
print("\xe2\x9d\x8c Core missing: 6")
print("\xe2\x8f\xba\xef\xb8\x8f Core exists-only: 3")
print("UNC core score: 80% (61 / 76)")
print("\nOptional documented extensions")
print("\xe2\x9c\x85 Optional passes: 16")
print("\xe2\x9b\x94 Optional behavior fails: 0")
print("\xe2\x8f\xad\xef\xb8\x8f Optional skipped: 7")
print("\xe2\x8f\xba\xef\xb8\x8f Optional exists-only: 0")
print("\xe2\x8f\xba\xef\xb8\x8f Optional missing: 66")
print("\n\xe2\x9d\x8c Missing core functions:")
print("  filtergc -> filtergc, firesignal -> firesignal, getcallingscript -> getcallingscript, getfunctionhash -> getfunctionhash, replicatesignal -> replicatesignal, restorefunction -> restorefunction")
print("\n\xe2\x8f\xad\xef\xb8\x8f Skipped optional functions:")
print("  rconsoleclear \xe2\x80\xa2 rconsole skipped: user chose no, rconsolecreate \xe2\x80\xa2 rconsole skipped: user chose no, rconsoledestroy \xe2\x80\xa2 rconsole skipped: user chose no, rconsoleinfo \xe2\x80\xa2 rconsole skipped: user chose no, rconsoleinput \xe2\x80\xa2 rconsole skipped: user chose no, rconsoleprint \xe2\x80\xa2 rconsole skipped: user chose no, rconsolewarn \xe2\x80\xa2 rconsole skipped: user chose no")
print("\n\xe2\x9b\x94 Core behavior failures:")
print("  debug.getconstant - could not find expected constant\n  debug.getconstants - constants table did not include expected string\n  debug.getupvalue - debug.getupvalue returned the wrong value\n  debug.getupvalues - upvalue was not present\n  debug.setconstant - debug.setconstant did not change the constant\n  debug.setstack - debug.setstack did not update the stack value\n  debug.setupvalue - debug.setupvalue did not update the upvalue\n  getrenv - getrenv().game must match game\n  hookfunction - hookfunction did not replace behavior")
print("\nVerdict: Partial UNC compatibility. Several core functions are missing or broken.")