game:GetService("HttpService")
game:GetService("RunService")
game:GetService("Players")
game:GetService("UserInputService")
game:GetService("ReplicatedStorage")
game:GetService("Debris")
game:GetService("Workspace")
game:GetService("TextChatService")
game:GetService("StarterGui")
game.ReplicatedStorage.WaitForChild(game.ReplicatedStorage, "GrabEvents", 5)
game.ReplicatedStorage.WaitForChild(game.ReplicatedStorage, "MenuToys", 5)
game.ReplicatedStorage.WaitForChild(game.ReplicatedStorage, "CharacterEvents", 5)
GrabEvents:WaitForChild("SetNetworkOwner", 5)
CharacterEvents:WaitForChild("Struggle", 5)
GrabEvents:WaitForChild("CreateGrabLine", 5)
GrabEvents:WaitForChild("DestroyGrabLine", 5)
MenuToys:WaitForChild("DestroyToy", 5)
game.Players.LocalPlayer.CharacterAdded:Connect(function() end)
game:GetService("RunService").Heartbeat:Connect(function() end)
error("HttpGet is not a valid member of DataModel")